services:
    cdo_blog.twig.page_extension:
        class: Cdo\BlogBundle\Extension\PageExtension
        arguments:
            container: "@service_container"
            doctrine: "@doctrine"
        tags:
            - { name: twig.extension }
    cdo_blog.twig.globals_blog_extension:
        class: Cdo\BlogBundle\Extension\GlobalsBlogExtension
        arguments: 
            container: "@service_container"
            request: "@request_stack"
        tags:
            - { name: twig.extension }