cdo_client:
    resource: "@CdoClientBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

ptm_site:
    resource: "@PtmSiteBundle/Resources/config/routing.yml"
    prefix:   /

cdo_account:
    resource: "@CdoAccountBundle/Resources/config/routing.yml"
    prefix:   /

cdo_user:
    resource: "@CdoUserBundle/Resources/config/routing.yml"
    prefix:   /{subdomain}

cdo_site:
    resource: "@CdoSiteBundle/Resources/config/routing.yml"
    prefix:   /{subdomain}

cdo_media:
    resource: "@CdoMediaBundle/Resources/config/routing.yml"
    prefix:   /{subdomain}

cdo_blog:
    resource: "@CdoBlogBundle/Resources/config/routing.yml"
    prefix:   /{subdomain}
#    requirements:
#        subdomain: "^(?!.*(login|logout)$).*" # GP_bug