parameters:

services:
    cdo_site.listener.subdomain_listener:
        class: Cdo\SiteBundle\Listener\SubdomainListener
        arguments:
            container: "@service_container"
            context: "@security.context"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: twig.extension }
    cdo_site.twig.menu_extension:
        class: Cdo\SiteBundle\Extension\MenuExtension
        arguments:
            container: "@service_container"
            doctrine: "@doctrine"
        tags:
            - { name: twig.extension }
    cdo_site.twig.params_extension:
        class: Cdo\SiteBundle\Extension\ParamsExtension
        arguments:
            container: "@service_container"
            doctrine: "@doctrine"
        tags:
            - { name: twig.extension }
    cdo_site.twig.styles_extension:
        class: Cdo\SiteBundle\Extension\StylesExtension
        arguments:
            container: "@service_container"
            doctrine: "@doctrine"
        tags:
            - { name: twig.extension }
    cdo_site.twig.globals_extension:
        class: Cdo\SiteBundle\Extension\GlobalsExtension
        arguments: 
            container: "@service_container"
            request: "@request_stack"
        tags:
            - { name: twig.extension }
