parameters:

services:
    cdo_site.listener.subdomain_listener:
        class: Cdo\SiteBundle\Listener\SubdomainListener
        arguments:
            container: "@service_container"
            context: "@security.context"
            router: "@router"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: twig.extension }
    cdo_site.twig.menu_extension:
        class: Cdo\SiteBundle\Extension\MenuExtension
        arguments:
            container: "@service_container"
            doctrine: "@doctrine"
        tags:
            - { name: twig.extension }
    cdo_site.twig.params_extension:
        class: Cdo\SiteBundle\Extension\ParamsExtension
        arguments:
            container: "@service_container"
            doctrine: "@doctrine"
        tags:
            - { name: twig.extension }
    cdo_site.twig.styles_extension:
        class: Cdo\SiteBundle\Extension\StylesExtension
        arguments:
            container: "@service_container"
            doctrine: "@doctrine"
        tags:
            - { name: twig.extension }
    cdo_site.twig.globals_site_extension:
        class: Cdo\SiteBundle\Extension\GlobalsSiteExtension
        arguments: 
            container: "@service_container"
            request: "@request_stack"
        tags:
            - { name: twig.extension }
